import { primitiveColors, semanticColors } from "./colors";
import {
  borderTokens,
  breakpointTokens,
  radiusTokens,
  screenTokens,
  sizeTokens,
  spacingTokens,
} from "./layout";
import {
  fontFamilyTokens,
  fontSizeTokens,
  fontWeightTokens,
  letterSpacingTokens,
  lineHeightTokens,
} from "./typography";

export type CssVariableMap = Record<`--${string}`, string | number>;

const px = (value: number) => `${value}px`;

const primitiveCssVariables = Object.fromEntries(
  Object.entries(primitiveColors).flatMap(([family, scale]) =>
    Object.entries(scale).map(([step, value]) => [
      `--${family}-${step}`,
      value,
    ]),
  ),
) as CssVariableMap;

const layoutCssVariables: CssVariableMap = {
  "--spacing-0": px(spacingTokens[0]),
  "--spacing-2xs": px(spacingTokens["2xs"]),
  "--spacing-xs": px(spacingTokens.xs),
  "--spacing-sm": px(spacingTokens.sm),
  "--spacing-md": px(spacingTokens.md),
  "--spacing-lg": px(spacingTokens.lg),
  "--spacing-xl": px(spacingTokens.xl),
  "--spacing-2xl": px(spacingTokens["2xl"]),
  "--spacing-3xl": px(spacingTokens["3xl"]),
  "--spacing-4xl": px(spacingTokens["4xl"]),
  "--spacing-5xl": px(spacingTokens["5xl"]),
  "--spacing-6xl": px(spacingTokens["6xl"]),
  "--radius-none": px(radiusTokens.none),
  "--radius-xs": px(radiusTokens.xs),
  "--radius-sm": px(radiusTokens.sm),
  "--radius-md": px(radiusTokens.md),
  "--radius-lg": px(radiusTokens.lg),
  "--radius-xl": px(radiusTokens.xl),
  "--radius-2xl": px(radiusTokens["2xl"]),
  "--radius-pill": px(radiusTokens.pill),
  "--size-sidebar-expanded": px(sizeTokens.sidebarExpanded),
  "--size-sidebar-collapsed": px(sizeTokens.sidebarCollapsed),
  "--size-topbar": px(sizeTokens.topbar),
  "--size-bottom-nav": px(sizeTokens.bottomNav),
  "--size-control-sm": px(sizeTokens.controlSm),
  "--size-control-md": px(sizeTokens.controlMd),
  "--size-control-lg": px(sizeTokens.controlLg),
  "--size-touch-min": px(sizeTokens.touchMin),
  "--size-icon-sm": px(sizeTokens.iconSm),
  "--size-icon-md": px(sizeTokens.iconMd),
  "--size-icon-lg": px(sizeTokens.iconLg),
  "--size-avatar-sm": px(sizeTokens.avatarSm),
  "--size-avatar-md": px(sizeTokens.avatarMd),
  "--size-avatar-lg": px(sizeTokens.avatarLg),
  "--size-content-max": px(sizeTokens.contentMax),
  "--border-thin": px(borderTokens.thin),
  "--border-thick": px(borderTokens.thick),
  "--bp-tablet": px(breakpointTokens.tablet),
  "--bp-desktop": px(breakpointTokens.desktop),
  "--screen-mobile": px(screenTokens.mobile),
  "--screen-tablet": px(screenTokens.tablet),
  "--screen-desktop": px(screenTokens.desktop),
};

const typographyCssVariables: CssVariableMap = {
  "--font-family-display": fontFamilyTokens.display,
  "--font-family-body": fontFamilyTokens.body,
  "--font-weight-regular": fontWeightTokens.regular,
  "--font-weight-medium": fontWeightTokens.medium,
  "--font-weight-semibold": fontWeightTokens.semibold,
  "--font-weight-bold": fontWeightTokens.bold,
  "--font-size-xs": px(fontSizeTokens.xs),
  "--font-size-sm": px(fontSizeTokens.sm),
  "--font-size-md": px(fontSizeTokens.md),
  "--font-size-lg": px(fontSizeTokens.lg),
  "--font-size-xl": px(fontSizeTokens.xl),
  "--font-size-2xl": px(fontSizeTokens["2xl"]),
  "--font-size-3xl": px(fontSizeTokens["3xl"]),
  "--font-size-4xl": px(fontSizeTokens["4xl"]),
  "--font-size-5xl": px(fontSizeTokens["5xl"]),
  "--font-size-6xl": px(fontSizeTokens["6xl"]),
  "--line-height-xs": px(lineHeightTokens.xs),
  "--line-height-sm": px(lineHeightTokens.sm),
  "--line-height-md": px(lineHeightTokens.md),
  "--line-height-lg": px(lineHeightTokens.lg),
  "--line-height-xl": px(lineHeightTokens.xl),
  "--line-height-2xl": px(lineHeightTokens["2xl"]),
  "--line-height-3xl": px(lineHeightTokens["3xl"]),
  "--line-height-4xl": px(lineHeightTokens["4xl"]),
  "--line-height-5xl": px(lineHeightTokens["5xl"]),
  "--line-height-6xl": px(lineHeightTokens["6xl"]),
  "--letter-spacing-tight": px(letterSpacingTokens.tight),
  "--letter-spacing-normal": px(letterSpacingTokens.normal),
  "--letter-spacing-wide": px(letterSpacingTokens.wide),
  "--letter-spacing-caps": px(letterSpacingTokens.caps),
};

function createSemanticCssVariables(
  colors: (typeof semanticColors)[keyof typeof semanticColors],
): CssVariableMap {
  return {
    "--bg-canvas": colors.bg.canvas,
    "--bg-surface": colors.bg.surface,
    "--bg-surface-alt": colors.bg.surfaceAlt,
    "--bg-surface-sunken": colors.bg.surfaceSunken,
    "--bg-inverse": colors.bg.inverse,
    "--bg-overlay": colors.bg.overlay,
    "--border-subtle": colors.border.subtle,
    "--border-default": colors.border.default,
    "--border-strong": colors.border.strong,
    "--border-inverse": colors.border.inverse,
    "--border-focus": colors.border.focus,
    "--text-primary": colors.text.primary,
    "--text-secondary": colors.text.secondary,
    "--text-placeholder": colors.text.placeholder,
    "--text-disabled": colors.text.disabled,
    "--text-inverse": colors.text.inverse,
    "--text-inverse-secondary": colors.text.inverseSecondary,
    "--text-link": colors.text.link,
    "--text-on-primary": colors.text.onPrimary,
    "--primary-solid": colors.primary.solid,
    "--primary-solid-hover": colors.primary.solidHover,
    "--primary-solid-pressed": colors.primary.solidPressed,
    "--primary-subtle": colors.primary.subtle,
    "--primary-border": colors.primary.border,
    "--primary-text": colors.primary.text,
    "--accent-subtle": colors.accent.subtle,
    "--accent-solid": colors.accent.solid,
    "--accent-border": colors.accent.border,
    "--accent-text": colors.accent.text,
    "--status-success-subtle": colors.status.success.subtle,
    "--status-success-solid": colors.status.success.solid,
    "--status-success-border": colors.status.success.border,
    "--status-success-text": colors.status.success.text,
    "--status-success-on-solid": colors.status.success.onSolid,
    "--status-warning-subtle": colors.status.warning.subtle,
    "--status-warning-solid": colors.status.warning.solid,
    "--status-warning-border": colors.status.warning.border,
    "--status-warning-text": colors.status.warning.text,
    "--status-warning-on-solid": colors.status.warning.onSolid,
    "--status-danger-subtle": colors.status.danger.subtle,
    "--status-danger-solid": colors.status.danger.solid,
    "--status-danger-solid-hover": colors.status.danger.solidHover,
    "--status-danger-border": colors.status.danger.border,
    "--status-danger-text": colors.status.danger.text,
    "--status-danger-on-solid": colors.status.danger.onSolid,
    "--status-neutral-subtle": colors.status.neutral.subtle,
    "--status-neutral-solid": colors.status.neutral.solid,
    "--status-neutral-border": colors.status.neutral.border,
    "--status-neutral-text": colors.status.neutral.text,
    "--status-neutral-on-solid": colors.status.neutral.onSolid,
    "--status-info-subtle": colors.status.info.subtle,
    "--status-info-solid": colors.status.info.solid,
    "--status-info-border": colors.status.info.border,
    "--status-info-text": colors.status.info.text,
    "--status-info-on-solid": colors.status.info.onSolid,
    "--sidebar-bg": colors.sidebar.bg,
    "--sidebar-item-active-bg": colors.sidebar.itemActiveBg,
    "--sidebar-item-hover-bg": colors.sidebar.itemHoverBg,
    "--sidebar-border": colors.sidebar.border,
    "--sidebar-text": colors.sidebar.text,
    "--sidebar-text-active": colors.sidebar.textActive,
    "--sidebar-text-muted": colors.sidebar.textMuted,
    "--skeleton-base": colors.skeleton.base,
  };
}

const sharedCssVariables: CssVariableMap = {
  ...primitiveCssVariables,
  ...layoutCssVariables,
  ...typographyCssVariables,
};

export const designSystemCssVariables = {
  light: {
    ...sharedCssVariables,
    ...createSemanticCssVariables(semanticColors.light),
  },
  dark: {
    ...sharedCssVariables,
    ...createSemanticCssVariables(semanticColors.dark),
  },
} as const;
