/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/autenticacao/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autenticar usuário
         * @description Autentica por e-mail e senha. Cria sessão normal ou emite token restrito para troca obrigatória de senha.
         */
        post: operations["autenticarUsuario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autenticacao/alterar-senha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Alterar senha
         * @description Permite troca obrigatória com token TROCA_SENHA ou troca voluntária com sessão normal. Após o sucesso, exige novo login.
         */
        post: operations["alterarSenha"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verifica se o processo da aplicação está ativo */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verifica dependências necessárias para receber tráfego */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "error";
                            checks: {
                                /** @enum {string} */
                                database: "up" | "down";
                                /** @enum {string} */
                                cache: "up" | "down";
                            };
                        };
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "error";
                            checks: {
                                /** @enum {string} */
                                database: "up" | "down";
                                /** @enum {string} */
                                cache: "up" | "down";
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    autenticarUsuario: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    senha: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken: string;
                        /** @enum {string} */
                        tokenType: "Bearer";
                        /** @enum {integer} */
                        expiresIn: 900;
                    } | {
                        tokenTrocaSenha: string;
                        /** @enum {string} */
                        tokenType: "TROCA_SENHA";
                        /** @enum {integer} */
                        expiresIn: 900;
                        /** @enum {boolean} */
                        trocaSenhaObrigatoria: true;
                    };
                };
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        timestamp: string;
                        status: number;
                        codigo: string;
                        titulo: string;
                        mensagem: string;
                        endpoint: string;
                        /** Format: uuid */
                        correlationId: string;
                        erros?: {
                            campo: string;
                            codigo: string;
                            mensagem: string;
                        }[];
                    };
                };
            };
            /** @description Default Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        timestamp: string;
                        status: number;
                        codigo: string;
                        titulo: string;
                        mensagem: string;
                        endpoint: string;
                        /** Format: uuid */
                        correlationId: string;
                        erros?: {
                            campo: string;
                            codigo: string;
                            mensagem: string;
                        }[];
                    };
                };
            };
            /** @description Default Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        timestamp: string;
                        status: number;
                        codigo: string;
                        titulo: string;
                        mensagem: string;
                        endpoint: string;
                        /** Format: uuid */
                        correlationId: string;
                        erros?: {
                            campo: string;
                            codigo: string;
                            mensagem: string;
                        }[];
                    };
                };
            };
            /** @description Default Response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        timestamp: string;
                        status: number;
                        codigo: string;
                        titulo: string;
                        mensagem: string;
                        endpoint: string;
                        /** Format: uuid */
                        correlationId: string;
                        erros?: {
                            campo: string;
                            codigo: string;
                            mensagem: string;
                        }[];
                    };
                };
            };
            /** @description Default Response */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        timestamp: string;
                        status: number;
                        codigo: string;
                        titulo: string;
                        mensagem: string;
                        endpoint: string;
                        /** Format: uuid */
                        correlationId: string;
                        erros?: {
                            campo: string;
                            codigo: string;
                            mensagem: string;
                        }[];
                    };
                };
            };
            /** @description Default Response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        timestamp: string;
                        status: number;
                        codigo: string;
                        titulo: string;
                        mensagem: string;
                        endpoint: string;
                        /** Format: uuid */
                        correlationId: string;
                        erros?: {
                            campo: string;
                            codigo: string;
                            mensagem: string;
                        }[];
                    };
                };
            };
            /** @description Default Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        timestamp: string;
                        status: number;
                        codigo: string;
                        titulo: string;
                        mensagem: string;
                        endpoint: string;
                        /** Format: uuid */
                        correlationId: string;
                        erros?: {
                            campo: string;
                            codigo: string;
                            mensagem: string;
                        }[];
                    };
                };
            };
        };
    };
    alterarSenha: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    senhaAtual?: string;
                    novaSenha: string;
                    confirmacaoNovaSenha: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        timestamp: string;
                        status: number;
                        codigo: string;
                        titulo: string;
                        mensagem: string;
                        endpoint: string;
                        /** Format: uuid */
                        correlationId: string;
                        erros?: {
                            campo: string;
                            codigo: string;
                            mensagem: string;
                        }[];
                    };
                };
            };
            /** @description Default Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        timestamp: string;
                        status: number;
                        codigo: string;
                        titulo: string;
                        mensagem: string;
                        endpoint: string;
                        /** Format: uuid */
                        correlationId: string;
                        erros?: {
                            campo: string;
                            codigo: string;
                            mensagem: string;
                        }[];
                    };
                };
            };
            /** @description Default Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        timestamp: string;
                        status: number;
                        codigo: string;
                        titulo: string;
                        mensagem: string;
                        endpoint: string;
                        /** Format: uuid */
                        correlationId: string;
                        erros?: {
                            campo: string;
                            codigo: string;
                            mensagem: string;
                        }[];
                    };
                };
            };
            /** @description Default Response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        timestamp: string;
                        status: number;
                        codigo: string;
                        titulo: string;
                        mensagem: string;
                        endpoint: string;
                        /** Format: uuid */
                        correlationId: string;
                        erros?: {
                            campo: string;
                            codigo: string;
                            mensagem: string;
                        }[];
                    };
                };
            };
            /** @description Default Response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        timestamp: string;
                        status: number;
                        codigo: string;
                        titulo: string;
                        mensagem: string;
                        endpoint: string;
                        /** Format: uuid */
                        correlationId: string;
                        erros?: {
                            campo: string;
                            codigo: string;
                            mensagem: string;
                        }[];
                    };
                };
            };
            /** @description Default Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        timestamp: string;
                        status: number;
                        codigo: string;
                        titulo: string;
                        mensagem: string;
                        endpoint: string;
                        /** Format: uuid */
                        correlationId: string;
                        erros?: {
                            campo: string;
                            codigo: string;
                            mensagem: string;
                        }[];
                    };
                };
            };
        };
    };
}
